name: Deploy
on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write # For peaceiris/actions-gh-pages
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: "! inputs.is_pr"
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build
          destination_dir: ./docs
