name: Deploy
on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For peaceiris/actions-gh-pages
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: "! inputs.is_pr"
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build
          destination_dir: ./docs
