---
name: Deploy GitHub Pages
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
permissions: {}
jobs:
  deploy-doc:
    uses: ./.github/workflows/workflow_call_deploy.yaml
    permissions:
      contents: write
      issues: write
