name: Deploy
on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: write # For peaceiris/actions-gh-pages
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: npm run build
      - uses: suzuki-shunsuke/gh-pages-action@9f11bf1233ad98c3cef0abdebe0e9b28f76feab7 # v0.0.2
        if: "! inputs.is_pr"
        with:
          publish_dir: build
          destination_dir: docs
