name: Deploy
on:
  workflow_call:
    inputs:
      is_pr:
        required: true
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # For peaceiris/actions-gh-pages
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: npm run build
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3.9.3
        if: "! inputs.is_pr"
        with:
          github_token: ${{ github.token }}
          publish_dir: ./build
          destination_dir: ./docs
